version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npm run test

  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npx semantic-release

workflows:
  version: 2
  semantic-release:
    jobs:
      - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
