name: CI @ Test

on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node: ['14', '16']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Build & Test
        run: |
          npm ci
          npm run build
          npm run test
