name: test

on:
  push:
    branches: [master]
    paths-ignore: ['docs/**']
  pull_request:
    paths-ignore: ['docs/**']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node Active LTS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          architecture: 'x64'
      - name: Install Deps
        run: npm ci
      - name: Build, Test & Coverage
        run: |
          npm run build
          npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
