name: test

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node: [14]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install Deps
        run: npm ci
      - name: Build & Test
        run: |
          npm run build
          npm run test
